### ISSUE TITLE
Prevent SIGABORT in native calls

### ISSUE THREAD

**Issue by sgladkov** [zone117x/Secp256k1.Net#16]
C++ library uses `CHECK_ARG` macro in many functions,  this macro calls `abort()` by default if some argument has incorrect value. It is difficult to process `SIGABORT` signal in dotnet app, and error is not so serious to crash the app. So it would be great to prevent `abort()` call in this case. It can be done with changing default error callback during the context initialization or by verifying in dotnet code (with throwing exceptions) all arguments  which are checked with `CHECK_ARG` macro in native code. 

In our case it was invalid `recoveryId` value for `secp256k1_ecdsa_recoverable_signature_parse_compact` for example.

**Comment by zone117x** [comment]
@sgladkov would you be able to open a PR for the first approach you have described?

**Comment by sgladkov** [comment]
I'll try to do it in a several days
