### ISSUE TITLE
Secp256k1.Ecdh() fails when run in x86 mode

### ISSUE THREAD

**Issue by AyrA** [zone117x/Secp256k1.Net#17]
When the project is set to target x86 instead of AnyCPU the call to `Secp256k1.Ecdh()` fails when supplying a custom hash function.

```
System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
```

**Comment by zone117x** [comment]
Can you include sample code that can easily reproduce this?

**Comment by AyrA** [comment]
I'm sorry, I do not have the code anymore for this because I've switched to a different library.
