### ISSUE TITLE
Publickey generation difference

### ISSUE THREAD

**Issue by MajMcCloud** [zone117x/Secp256k1.Net#19]
Hey!

im trying to get from a private key to the public key  by using your example. 
Want to use it to get from a bitcoin private key to public key.

Interestingly the public key what comes out is not the same as with other libraries, so something seems to be wrong.

Here is my code:

```csharp
var secp256k1 = new Secp256k1();
var RND = RandomNumberGenerator.Create();

// Generate a private key.
var privateKey = new byte[32];
do { RND.GetBytes(privateKey); }
while (!secp256k1.SecretKeyVerify(privateKey));


// Create public key from private key.
var publicKey = new byte[64];
secp256k1.PublicKeyCreate(publicKey, privateKey);


byte[] pub = new byte[65];
Array.Copy(publicKey, 0, pub, 1, publicKey.Length);
pub[0] = 4;

```

Example:

Random PrivateKey: e435df40bac81cd8f43887be96338cf2bbe8ea12831d0cc33672b6e77de91e6d
PublicKey (with this code): 04f61dda3e22956223c27d608bc0c9b45182d2ecbbdc631c8595ca868a6b0d5d7e401d3eb38c7d2f6dd5607f1972650574bf5548d734bf277dc121f9f313af9e00
PublicKey with NBitcoin library: 047e5d0d6b8a86ca95851c63dcbbecd28251b4c9c08b607dc2236295223eda1df6009eaf13f3f921c17d27bf34d74855bf74056572197f60d56d2f7d8cb33e1d40

Thank you !
Warm regards
Florian

**Comment by zone117x** [comment]
Hi! You need to serialize the public key. Given your examples, this is working as expected:
```cs
using (var secp256k1 = new Secp256k1())
{
    Span<byte> privateKey = "e435df40bac81cd8f43887be96338cf2bbe8ea12831d0cc33672b6e77de91e6d".HexToBytes();
    Span<byte> publicKeyOutput = new byte[Secp256k1.PUBKEY_LENGTH];
    bool result = secp256k1.PublicKeyCreate(publicKeyOutput, privateKey);
    Assert.True(result);

    // Serialize the public key
    Span<byte> serializedKey = new byte[Secp256k1.SERIALIZED_UNCOMPRESSED_PUBKEY_LENGTH];
    result = secp256k1.PublicKeySerialize(serializedKey, publicKeyOutput);
    Assert.True(result);

    var pubKeyHex = serializedKey.ToHexString();
    var expectedPubKey =
        "0x047e5d0d6b8a86ca95851c63dcbbecd28251b4c9c08b607dc2236295223eda1df6009eaf13f3f921c17d27bf34d74855bf74056572197f60d56d2f7d8cb33e1d40";

    Assert.Equal(expectedPubKey, pubKeyHex);
}
```
